import { Mail } from 'lucide-react';
import type { Metadata } from "next";
import "./../../assets/styles/globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log()
  return (
    <html lang="en">
      <body
        className={`antialiased bg-white min-h-screen flex flex-col`}
      >
          <div className="flex-1 grid justify-center items-center ">
            {children}
          </div>
            <footer className="p-6 flex justify-between text-gray-600 text-sm">
              <span className="flex items-center gap-4">
              <Mail className="text-[#667085] w-[1.7rem] h-[1.3rem]" />
              <a href="mailto:support@3ventiz.com" className="xs-text">support@3ventiz.com</a>
              </span>
              <span className="xs-text">© 3ventiz2025</span>
            </footer>
      </body>
    </html>
  );
}
