import { AuthProviders } from "@/context/authProvider";
import DashboardLayout from "@/layouts/dashboardLayout";
import type { Metadata } from "next";
import "./../../assets/styles/globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
      </head>
      <body
        className={` antialiased`}
      >
        {/* <NoSSR>
        </NoSSR> */}
          <AuthProviders>
            <DashboardLayout children={children} />
          </AuthProviders>
      </body>
    </html>
  );
}
