import {default as UserDetailModal} from "./userDetailModal"
import {default as AdminCreateForm} from "./adminCreateForm"
import {default as AdminTable} from "./adminTable"
import {default as EditRoleForm} from "./editPermission"
import {default as UserTicketHistory} from "./userTicketHistory"
import {default as UserTable} from "./userTable"